name: oauth_dio
description: A customizable oauth client with token storage and interceptors for dio
version: 0.2.7
homepage: https://github.com/salomaosnff/oauth_dio

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dio: ^4.0.0

dev_dependencies:
  test: ^1.21.0
